import '../../app/constants.dart';
import 'learning_activity.dart';

class SeedData {
  static final activities = <LearningActivity>[
    ..._math,
    ..._letters,
    ..._art,
    ..._logic,
  ];

  static List<LearningActivity> byModule(ModuleId module) {
    final items = activities
        .where((item) => item.moduleId == module.id)
        .toList();
    items.sort(
      (a, b) => a.level == b.level
          ? a.id.compareTo(b.id)
          : a.level.compareTo(b.level),
    );
    return items;
  }

  static LearningActivity _a(
    String id,
    String module,
    int level,
    String type,
    String question,
    List<String> options,
    String correct,
    String explanation,
    List<String> visual,
  ) {
    return LearningActivity(
      id: id,
      moduleId: module,
      level: level,
      type: type,
      question: question,
      options: options,
      correctAnswer: correct,
      explanation: explanation,
      visualItems: visual,
    );
  }

  static final _math = <LearningActivity>[
    _a(
      'math_01',
      'math',
      1,
      'contador',
      'Cuenta las manzanas.',
      ['1', '2', '3', '4'],
      '3',
      'Tocamos 3 veces porque hay 3 manzanas.',
      ['apple', 'apple', 'apple'],
    ),
    _a(
      'math_02',
      'math',
      1,
      'contador',
      'Cuenta los soles.',
      ['1', '2', '3', '4'],
      '2',
      'Hay 2 soles.',
      ['sun', 'sun'],
    ),
    _a(
      'math_03',
      'math',
      2,
      'contador',
      'Cuenta las estrellas.',
      ['4', '5', '6', '7'],
      '6',
      'Son 6 estrellas.',
      ['star', 'star', 'star', 'star', 'star', 'star'],
    ),
    _a(
      'math_04',
      'math',
      2,
      'contador',
      'Cuenta los globos.',
      ['6', '7', '8', '9'],
      '8',
      'Hay 8 globos.',
      [
        'balloon',
        'balloon',
        'balloon',
        'balloon',
        'balloon',
        'balloon',
        'balloon',
        'balloon',
      ],
    ),
    _a(
      'math_05',
      'math',
      3,
      'suma',
      '2 naranjas y 2 naranjas son...',
      ['3', '4', '5', '6'],
      '4',
      '2 mas 2 es 4.',
      ['orange', 'orange', '+', 'orange', 'orange'],
    ),
    _a(
      'math_06',
      'math',
      3,
      'suma',
      '3 peras y 1 pera son...',
      ['2', '3', '4', '5'],
      '4',
      '3 mas 1 es 4.',
      ['pear', 'pear', 'pear', '+', 'pear'],
    ),
    _a(
      'math_07',
      'math',
      4,
      'resta',
      'Habia 5 juguetes. Quitamos 2. Quedan...',
      ['1', '2', '3', '4'],
      '3',
      '5 menos 2 es 3.',
      ['toy', 'toy', 'toy', 'toy', 'toy', '-2'],
    ),
    _a(
      'math_08',
      'math',
      4,
      'resta',
      'Habia 7 caramelos. Quitamos 3. Quedan...',
      ['3', '4', '5', '6'],
      '4',
      '7 menos 3 es 4.',
      ['candy', 'candy', 'candy', 'candy', 'candy', 'candy', 'candy', '-3'],
    ),
    _a(
      'math_09',
      'math',
      5,
      'faltante',
      'Completa: 4 + ? = 6',
      ['1', '2', '3', '4'],
      '2',
      'Faltan 2 para llegar a 6.',
      ['4', '+', '?', '=', '6'],
    ),
    _a(
      'math_10',
      'math',
      5,
      'faltante',
      'Completa: 7 - ? = 5',
      ['1', '2', '3', '4'],
      '2',
      'Quitamos 2 para quedar en 5.',
      ['7', '-', '?', '=', '5'],
    ),
    _a(
      'math_11',
      'math',
      6,
      'contador',
      'Cuenta los corazones.',
      ['8', '9', '10', '11'],
      '10',
      'Hay 10 corazones.',
      [
        'heart',
        'heart',
        'heart',
        'heart',
        'heart',
        'heart',
        'heart',
        'heart',
        'heart',
        'heart',
      ],
    ),
    _a(
      'math_12',
      'math',
      6,
      'comparacion',
      'Que grupo tiene mas?',
      ['Grupo A', 'Grupo B', 'Iguales', 'Ninguno'],
      'Grupo B',
      'El grupo B tiene mas puntos.',
      ['group_a_3', 'group_b_5'],
    ),
    _a(
      'math_13',
      'math',
      7,
      'suma',
      '5 estrellas y 3 estrellas son...',
      ['6', '7', '8', '9'],
      '8',
      '5 mas 3 es 8.',
      ['star', 'star', 'star', 'star', 'star', '+', 'star', 'star', 'star'],
    ),
    _a(
      'math_14',
      'math',
      7,
      'resta',
      '9 flores menos 4 flores son...',
      ['4', '5', '6', '7'],
      '5',
      '9 menos 4 es 5.',
      [
        'flower',
        'flower',
        'flower',
        'flower',
        'flower',
        'flower',
        'flower',
        'flower',
        'flower',
        '-4',
      ],
    ),
    _a(
      'math_15',
      'math',
      8,
      'secuencia numerica',
      'Que numero sigue? 2, 4, 6, ...',
      ['7', '8', '9', '10'],
      '8',
      'La secuencia avanza de 2 en 2.',
      ['2', '4', '6', '?'],
    ),
    _a(
      'math_16',
      'math',
      8,
      'secuencia numerica',
      'Que numero falta? 1, 3, ?, 7',
      ['4', '5', '6', '8'],
      '5',
      'Son numeros impares: 1, 3, 5, 7.',
      ['1', '3', '?', '7'],
    ),
    _a(
      'math_17',
      'math',
      9,
      'mixto',
      '6 + 2 - 1 es...',
      ['6', '7', '8', '9'],
      '7',
      '6 mas 2 es 8, menos 1 queda 7.',
      ['6', '+2', '-1'],
    ),
    _a(
      'math_18',
      'math',
      9,
      'mixto',
      '10 - 3 + 1 es...',
      ['7', '8', '9', '10'],
      '8',
      '10 menos 3 es 7, mas 1 es 8.',
      ['10', '-3', '+1'],
    ),
    _a(
      'math_19',
      'math',
      10,
      'reto final',
      'Reto: 4 + 3 + 2 es...',
      ['7', '8', '9', '10'],
      '9',
      '4 mas 3 mas 2 es 9.',
      ['4', '+', '3', '+', '2'],
    ),
    _a(
      'math_20',
      'math',
      10,
      'reto final',
      'Reto: 12 - 5 es...',
      ['5', '6', '7', '8'],
      '7',
      '12 menos 5 es 7.',
      ['12', '-', '5'],
    ),
  ];

  static final _letters = <LearningActivity>[
    _a(
      'letters_01',
      'letters',
      1,
      'vocal',
      'Toca la vocal A.',
      ['A', 'E', 'I', 'O'],
      'A',
      'La vocal correcta es A.',
      ['A'],
    ),
    _a(
      'letters_02',
      'letters',
      1,
      'vocal',
      'Toca la vocal E.',
      ['A', 'E', 'I', 'U'],
      'E',
      'La vocal correcta es E.',
      ['E'],
    ),
    _a(
      'letters_03',
      'letters',
      2,
      'vocal inicial',
      'Avion empieza con...',
      ['A', 'E', 'O', 'U'],
      'A',
      'Avion empieza con A.',
      ['plane'],
    ),
    _a(
      'letters_04',
      'letters',
      2,
      'vocal inicial',
      'Sol empieza con...',
      ['A', 'E', 'I', 'S'],
      'S',
      'Sol empieza con S.',
      ['sun'],
    ),
    _a(
      'letters_05',
      'letters',
      3,
      'silaba',
      'Completa la pareja: MA - ...',
      ['ME', 'PA', 'SA', 'NO'],
      'ME',
      'MA y ME son silabas de la misma familia.',
      ['MA', 'ME'],
    ),
    _a(
      'letters_06',
      'letters',
      3,
      'silaba',
      'Que silaba suena como PA?',
      ['PA', 'LA', 'NO', 'SE'],
      'PA',
      'PA es la silaba indicada.',
      ['PA'],
    ),
    _a(
      'letters_07',
      'letters',
      4,
      'imagen palabra',
      'Que palabra corresponde?',
      ['SOL', 'PAN', 'OSO', 'MESA'],
      'SOL',
      'La imagen representa el sol.',
      ['sun'],
    ),
    _a(
      'letters_08',
      'letters',
      4,
      'imagen palabra',
      'Que palabra corresponde?',
      ['CASA', 'LUNA', 'SOPA', 'PATO'],
      'LUNA',
      'La imagen representa la luna.',
      ['moon'],
    ),
    _a(
      'letters_09',
      'letters',
      5,
      'completa palabra',
      'Completa: S_L',
      ['A', 'E', 'O', 'U'],
      'O',
      'SOL se escribe con O.',
      ['S', '_', 'L'],
    ),
    _a(
      'letters_10',
      'letters',
      5,
      'completa palabra',
      'Completa: P_N',
      ['A', 'E', 'I', 'O'],
      'A',
      'PAN se escribe con A.',
      ['P', '_', 'N'],
    ),
    _a(
      'letters_11',
      'letters',
      6,
      'arrastra',
      'Arrastra la palabra correcta para la imagen.',
      ['GATO', 'MESA', 'PATO', 'CASA'],
      'GATO',
      'La imagen representa GATO.',
      ['cat'],
    ),
    _a(
      'letters_12',
      'letters',
      6,
      'arrastra',
      'Arrastra la palabra correcta para la imagen.',
      ['RANA', 'ROSA', 'RISA', 'RUTA'],
      'RANA',
      'La imagen representa RANA.',
      ['frog'],
    ),
    _a(
      'letters_13',
      'letters',
      7,
      'ordenar',
      'Ordena la palabra: A - S - C - A',
      ['CASA', 'SACA', 'ASCA', 'COSA'],
      'CASA',
      'La palabra correcta es CASA.',
      ['A', 'S', 'C', 'A'],
    ),
    _a(
      'letters_14',
      'letters',
      7,
      'ordenar',
      'Ordena la palabra: O - S - O',
      ['OSO', 'SOO', 'OOS', 'SOS'],
      'OSO',
      'La palabra correcta es OSO.',
      ['O', 'S', 'O'],
    ),
    _a(
      'letters_15',
      'letters',
      8,
      'rima',
      'Que palabra rima con SOL?',
      ['COL', 'PAN', 'MESA', 'RANA'],
      'COL',
      'SOL y COL terminan parecido.',
      ['SOL'],
    ),
    _a(
      'letters_16',
      'letters',
      8,
      'rima',
      'Que palabra rima con PATO?',
      ['GATO', 'LUNA', 'SOL', 'PAN'],
      'GATO',
      'PATO y GATO terminan en ATO.',
      ['PATO'],
    ),
    _a(
      'letters_17',
      'letters',
      9,
      'lectura',
      'Lee y elige: La casa es...',
      ['grande', 'sol', 'pato', 'rojo'],
      'grande',
      'La frase queda: La casa es grande.',
      ['La casa es'],
    ),
    _a(
      'letters_18',
      'letters',
      9,
      'lectura',
      'Elige la palabra corta.',
      ['SOL', 'MARIPOSA', 'ELEFANTE', 'CARAMELO'],
      'SOL',
      'SOL tiene tres letras.',
      ['ABC'],
    ),
    _a(
      'letters_19',
      'letters',
      10,
      'reto final',
      'Reto: que palabra inicia con M?',
      ['MESA', 'PATO', 'LUNA', 'SOL'],
      'MESA',
      'MESA inicia con M.',
      ['M'],
    ),
    _a(
      'letters_20',
      'letters',
      10,
      'reto final',
      'Reto: completa MA _ O',
      ['N', 'S', 'P', 'L'],
      'N',
      'La palabra es MANO.',
      ['MA', '_', 'O'],
    ),
  ];

  static final _art = <LearningActivity>[
    _a(
      'art_01',
      'art',
      1,
      'pintado',
      'Pinta el circulo de rojo.',
      ['Rojo', 'Azul', 'Verde', 'Amarillo'],
      'Rojo',
      'El circulo queda rojo.',
      ['circle'],
    ),
    _a(
      'art_02',
      'art',
      1,
      'pintado',
      'Pinta el cuadrado de azul.',
      ['Rojo', 'Azul', 'Verde', 'Amarillo'],
      'Azul',
      'El cuadrado queda azul.',
      ['square'],
    ),
    _a(
      'art_03',
      'art',
      2,
      'forma',
      'Selecciona el triangulo.',
      ['Circulo', 'Triangulo', 'Cuadrado', 'Estrella'],
      'Triangulo',
      'El triangulo tiene 3 lados.',
      ['circle', 'triangle', 'square', 'star'],
    ),
    _a(
      'art_04',
      'art',
      2,
      'forma',
      'Selecciona el rectangulo.',
      ['Circulo', 'Rectangulo', 'Triangulo', 'Rombo'],
      'Rectangulo',
      'El rectangulo tiene lados largos y cortos.',
      ['circle', 'rectangle', 'triangle', 'diamond'],
    ),
    _a(
      'art_05',
      'art',
      3,
      'arrastra',
      'Arrastra el color calido.',
      ['Naranja', 'Azul', 'Verde', 'Morado'],
      'Naranja',
      'Naranja es un color calido.',
      ['fire'],
    ),
    _a(
      'art_06',
      'art',
      3,
      'arrastra',
      'Arrastra el color frio.',
      ['Azul', 'Rojo', 'Amarillo', 'Naranja'],
      'Azul',
      'Azul es un color frio.',
      ['snow'],
    ),
    _a(
      'art_07',
      'art',
      4,
      'clasificar',
      'Que figura tiene cuatro lados?',
      ['Cuadrado', 'Circulo', 'Ovalo', 'Estrella'],
      'Cuadrado',
      'El cuadrado tiene cuatro lados.',
      ['square'],
    ),
    _a(
      'art_08',
      'art',
      4,
      'clasificar',
      'Que figura es redonda?',
      ['Circulo', 'Triangulo', 'Rombo', 'Cuadrado'],
      'Circulo',
      'El circulo es redondo.',
      ['circle'],
    ),
    _a(
      'art_09',
      'art',
      5,
      'mezcla',
      'Rojo + amarillo forman...',
      ['Naranja', 'Verde', 'Morado', 'Azul'],
      'Naranja',
      'Rojo y amarillo forman naranja.',
      ['red', '+', 'yellow'],
    ),
    _a(
      'art_10',
      'art',
      5,
      'mezcla',
      'Azul + amarillo forman...',
      ['Verde', 'Naranja', 'Rosado', 'Marron'],
      'Verde',
      'Azul y amarillo forman verde.',
      ['blue', '+', 'yellow'],
    ),
    _a(
      'art_11',
      'art',
      6,
      'pintado',
      'Pinta la estrella de amarillo.',
      ['Rojo', 'Azul', 'Verde', 'Amarillo'],
      'Amarillo',
      'La estrella queda amarilla.',
      ['star'],
    ),
    _a(
      'art_12',
      'art',
      6,
      'pintado',
      'Pinta el triangulo de verde.',
      ['Rojo', 'Azul', 'Verde', 'Amarillo'],
      'Verde',
      'El triangulo queda verde.',
      ['triangle'],
    ),
    _a(
      'art_13',
      'art',
      7,
      'patron color',
      'Que color sigue? Rojo, azul, rojo...',
      ['Azul', 'Rojo', 'Verde', 'Amarillo'],
      'Azul',
      'El patron alterna rojo y azul.',
      ['red', 'blue', 'red', '?'],
    ),
    _a(
      'art_14',
      'art',
      7,
      'patron color',
      'Que color sigue? Verde, verde, amarillo...',
      ['Amarillo', 'Verde', 'Azul', 'Rojo'],
      'Amarillo',
      'El patron repite dos verdes y dos amarillos.',
      ['green', 'green', 'yellow', '?'],
    ),
    _a(
      'art_15',
      'art',
      8,
      'silueta',
      'Que forma completa la casita?',
      ['Triangulo', 'Circulo', 'Ovalo', 'Rombo'],
      'Triangulo',
      'El techo puede ser un triangulo.',
      ['square', '+', '?'],
    ),
    _a(
      'art_16',
      'art',
      8,
      'silueta',
      'Que forma puede ser una rueda?',
      ['Circulo', 'Cuadrado', 'Triangulo', 'Rombo'],
      'Circulo',
      'Una rueda tiene forma circular.',
      ['car', '?'],
    ),
    _a(
      'art_17',
      'art',
      9,
      'reto creativo',
      'Elige un color para un cielo de noche.',
      ['Azul', 'Rojo', 'Amarillo', 'Verde'],
      'Azul',
      'El cielo nocturno suele verse azul oscuro.',
      ['moon', 'star'],
    ),
    _a(
      'art_18',
      'art',
      9,
      'reto creativo',
      'Elige una forma para hacer una flor.',
      ['Circulo', 'Rectangulo', 'Rombo', 'Linea'],
      'Circulo',
      'Los petalos pueden dibujarse con circulos.',
      ['flower'],
    ),
    _a(
      'art_19',
      'art',
      10,
      'reto final',
      'Reto: que mezcla crea morado?',
      ['Rojo + azul', 'Azul + amarillo', 'Rojo + amarillo', 'Verde + azul'],
      'Rojo + azul',
      'Rojo y azul forman morado.',
      ['red', '+', 'blue'],
    ),
    _a(
      'art_20',
      'art',
      10,
      'reto final',
      'Reto: que figura tiene 3 lados?',
      ['Triangulo', 'Circulo', 'Cuadrado', 'Rectangulo'],
      'Triangulo',
      'El triangulo tiene 3 lados.',
      ['triangle'],
    ),
  ];

  static final _logic = <LearningActivity>[
    _a(
      'logic_01',
      'logic',
      1,
      'memoria',
      'Encuentra la pareja del sol.',
      ['sun', 'moon', 'star', 'cloud'],
      'sun',
      'Encontraste dos soles.',
      ['sun', 'moon', 'sun', 'star'],
    ),
    _a(
      'logic_02',
      'logic',
      1,
      'memoria',
      'Encuentra la pareja de la luna.',
      ['moon', 'sun', 'star', 'cloud'],
      'moon',
      'Encontraste dos lunas.',
      ['moon', 'sun', 'star', 'moon'],
    ),
    _a(
      'logic_03',
      'logic',
      2,
      'patron',
      'Que figura sigue?',
      ['Azul', 'Rojo', 'Amarillo', 'Verde'],
      'Azul',
      'El patron alterna rojo y azul.',
      ['red', 'blue', 'red', '?'],
    ),
    _a(
      'logic_04',
      'logic',
      2,
      'patron',
      'Que figura sigue?',
      ['Triangulo', 'Circulo', 'Cuadrado', 'Estrella'],
      'Triangulo',
      'El patron repite circulo y triangulo.',
      ['circle', 'triangle', 'circle', '?'],
    ),
    _a(
      'logic_05',
      'logic',
      3,
      'secuencia',
      'Ordena del mas pequeno al mas grande.',
      ['1-2-3', '3-2-1', '2-1-3', '1-3-2'],
      '1-2-3',
      'La secuencia correcta es 1, 2 y 3.',
      ['1', '2', '3'],
    ),
    _a(
      'logic_06',
      'logic',
      3,
      'secuencia',
      'Que viene despues de bebe?',
      ['nino', 'abuelo', 'adulto', 'anciano'],
      'nino',
      'La secuencia crece: bebe, nino, adulto.',
      ['bebe', '?', 'adulto'],
    ),
    _a(
      'logic_07',
      'logic',
      4,
      'clasificar',
      'Cual pertenece a frutas?',
      ['Manzana', 'Auto', 'Zapato', 'Mesa'],
      'Manzana',
      'La manzana es una fruta.',
      ['apple'],
    ),
    _a(
      'logic_08',
      'logic',
      4,
      'clasificar',
      'Cual pertenece a animales?',
      ['Gato', 'Silla', 'Sol', 'Pan'],
      'Gato',
      'Gato pertenece a animales.',
      ['cat'],
    ),
    _a(
      'logic_09',
      'logic',
      5,
      'intruso',
      'Encuentra el intruso.',
      ['Perro', 'Gato', 'Mesa', 'Pato'],
      'Mesa',
      'Mesa no pertenece al grupo de animales.',
      ['Perro', 'Gato', 'Mesa', 'Pato'],
    ),
    _a(
      'logic_10',
      'logic',
      5,
      'intruso',
      'Encuentra el intruso.',
      ['Rojo', 'Azul', 'Verde', 'Casa'],
      'Casa',
      'Casa no es un color.',
      ['red', 'blue', 'green', 'Casa'],
    ),
    _a(
      'logic_11',
      'logic',
      6,
      'arrastra',
      'Arrastra lo que se usa para escribir.',
      ['Lapiz', 'Pelota', 'Zapato', 'Taza'],
      'Lapiz',
      'El lapiz sirve para escribir.',
      ['pencil'],
    ),
    _a(
      'logic_12',
      'logic',
      6,
      'arrastra',
      'Arrastra lo que se come.',
      ['Pan', 'Libro', 'Auto', 'Silla'],
      'Pan',
      'El pan se come.',
      ['bread'],
    ),
    _a(
      'logic_13',
      'logic',
      7,
      'patron',
      'Que sigue? estrella, luna, estrella...',
      ['Luna', 'Estrella', 'Sol', 'Nube'],
      'Luna',
      'El patron alterna estrella y luna.',
      ['star', 'moon', 'star', '?'],
    ),
    _a(
      'logic_14',
      'logic',
      7,
      'patron',
      'Que sigue? A, B, A...',
      ['B', 'A', 'C', 'D'],
      'B',
      'El patron alterna A y B.',
      ['A', 'B', 'A', '?'],
    ),
    _a(
      'logic_15',
      'logic',
      8,
      'secuencia',
      'Que pasa primero?',
      ['semilla', 'flor', 'fruta', 'arbol'],
      'semilla',
      'Primero se planta una semilla.',
      ['?', 'plant', 'flower'],
    ),
    _a(
      'logic_16',
      'logic',
      8,
      'secuencia',
      'Que va antes de dormir?',
      ['ponerse pijama', 'despertar', 'almorzar', 'correr'],
      'ponerse pijama',
      'Antes de dormir nos preparamos.',
      ['moon'],
    ),
    _a(
      'logic_17',
      'logic',
      9,
      'memoria',
      'Encuentra la pareja de la estrella.',
      ['star', 'sun', 'moon', 'cloud'],
      'star',
      'Encontraste dos estrellas.',
      ['star', 'sun', 'star', 'moon', 'cloud', 'sun'],
    ),
    _a(
      'logic_18',
      'logic',
      9,
      'memoria',
      'Encuentra la pareja de la nube.',
      ['cloud', 'star', 'moon', 'sun'],
      'cloud',
      'Encontraste dos nubes.',
      ['cloud', 'star', 'moon', 'cloud', 'sun', 'star'],
    ),
    _a(
      'logic_19',
      'logic',
      10,
      'reto final',
      'Reto: que figura completa el patron?',
      ['Cuadrado', 'Triangulo', 'Circulo', 'Estrella'],
      'Cuadrado',
      'El patron repite cuadrado, triangulo, circulo.',
      ['square', 'triangle', 'circle', 'square', 'triangle', '?'],
    ),
    _a(
      'logic_20',
      'logic',
      10,
      'reto final',
      'Reto: cual no pertenece?',
      ['Zapato', 'Sandalia', 'Bota', 'Sopa'],
      'Sopa',
      'Sopa no es calzado.',
      ['Zapato', 'Sandalia', 'Bota', 'Sopa'],
    ),
  ];
}
